name: release

on:
  workflow_dispatch:
    inputs:
      prereleaseSlug:
        description: 'Prerelease slug (optional)'
        required: false
        default: ''
        type: choice
        options:
        - rc
        - beta
        - ''

jobs:
  build:
    uses: ./.github/workflows/part-build.yml
    secrets: inherit
    with:
      prereleaseSlug: ${{ inputs.prereleaseSlug }}
      checkTagIsUnique: true

  publish:
    uses: ./.github/workflows/part-publish.yml
    needs: build
    secrets: inherit 

  create-release:
    runs-on: ubuntu-latest
    needs: [build, publish]
    steps:
    - uses: actions/checkout@v3
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ needs.build.outputs.COALESCE_VERSION }}